import type { Language } from "./types";

export interface Translations {
  nav: {
    home: string;
    dailyCare: string;
    gpBridge: string;
    capture: string;
    reminders: string;
  };
  home: {
    title: string;
    subtitle: string;
    mostRecent: string;
    adherenceToday: string;
  };
  dailyCare: {
    title: string;
    subtitle: string;
    totalLogged: string;
    thisWeek: string;
    avgSeverity: string;
    recordSymptom: string;
    recentEntries: string;
    noSymptoms: string;
    symptomLabel: string;
    severityLabel: string;
    howItFeels: string;
    dateLabel: string;
    notesLabel: string;
    optional: string;
    customPlaceholder: string;
    descPlaceholder: string;
    notesPlaceholder: string;
    addVoiceNote: string;
    saveEntry: string;
    allFilter: string;
    symptomSeverity: string;
    voiceNote: string;
  };
  voice: {
    recording: string;
    stop: string;
    cancel: string;
    tapWhenDone: string;
  };
  severity: {
    veryMild: string;
    mild: string;
    moderate: string;
    quiteBad: string;
    severe: string;
  };
  trend: {
    improving: string;
    stable: string;
    worsening: string;
  };
  symptomNames: string[];
  gpBridge: {
    title: string;
    subtitle: string;
    whatSharingDoes: string;
    sharingExplanation: string;
    whatGPWillSee: string;
    symptomEntries: string;
    medicationAdherence: string;
    voiceNotes: string;
    aiSummary: string;
    included: string;
    yourAccessCode: string;
    giveCodeToGP: string;
    copyCode: string;
    copied: string;
    shareWithGP: string;
    sharedWithGP: string;
    sharedConfirmation: string;
    revokeAccess: string;
    entriesOverWeeks: (total: number, weeks: number) => string;
    voiceNoteCount: (n: number) => string;
  };
  capture: {
    title: string;
    subtitle: string;
    bmaTitle: string;
    bmaText: string;
    tapToRecord: string;
    transcriptionNote: string;
    consultationRecording: string;
    aiTranscription: string;
    autoGenerated: string;
    reRecord: string;
  };
  reminders: {
    title: string;
    subtitle: string;
    takenOfTotal: (taken: number, total: number) => string;
    allTaken: string;
    stillToTake: (n: number) => string;
    morning: string;
    afternoon: string;
    evening: string;
    taken: string;
    skip: string;
    skipped: string;
    footerNote: string;
  };
  chat: {
    title: string;
    subtitle: string;
    disclaimer: string;
    placeholder: string;
  };
}

const en: Translations = {
  nav: {
    home: "Home",
    dailyCare: "Daily Care",
    gpBridge: "GP Bridge",
    capture: "Capture",
    reminders: "Reminders",
  },
  home: {
    title: "Welcome, Maria",
    subtitle: "Your health, clearly tracked.",
    mostRecent: "Most recent",
    adherenceToday: "Adherence today",
  },
  dailyCare: {
    title: "Daily Care",
    subtitle: "Track how you feel, every day",
    totalLogged: "Total logged",
    thisWeek: "This week",
    avgSeverity: "Avg severity",
    recordSymptom: "Record a symptom",
    recentEntries: "Recent Entries",
    noSymptoms: "No symptoms logged yet.",
    symptomLabel: "Symptom",
    severityLabel: "Severity",
    howItFeels: "How does it feel?",
    dateLabel: "Date",
    notesLabel: "Notes",
    optional: "(optional)",
    customPlaceholder: "Or type a custom symptom…",
    descPlaceholder: "Describe how you are feeling…",
    notesPlaceholder: "Any additional context…",
    addVoiceNote: "Add voice note",
    saveEntry: "Save entry",
    allFilter: "All",
    symptomSeverity: "Symptom Severity",
    voiceNote: "1 voice note",
  },
  voice: {
    recording: "Recording",
    stop: "Stop",
    cancel: "Cancel",
    tapWhenDone: "Tap Stop when you are done",
  },
  severity: {
    veryMild: "Very mild",
    mild: "Mild",
    moderate: "Moderate",
    quiteBad: "Quite bad",
    severe: "Severe",
  },
  trend: {
    improving: "Improving",
    stable: "Stable",
    worsening: "Worsening",
  },
  symptomNames: [
    "Headache", "Tiredness", "Back Pain", "Nausea", "Dizziness",
    "Chest tightness", "Joint pain", "Breathlessness", "Stomach ache",
    "Anxiety", "Palpitations", "Swollen ankles",
  ],
  gpBridge: {
    title: "GP Bridge",
    subtitle: "Share your health picture with your GP",
    whatSharingDoes: "What does sharing do?",
    sharingExplanation:
      "Sharing gives your GP a clear, up-to-date picture of your recent symptoms, medication adherence, and voice notes — before your appointment, so they can prepare and you can make the most of your time together. No personal data leaves your device without your consent.",
    whatGPWillSee: "What your GP will see",
    symptomEntries: "Symptom entries",
    medicationAdherence: "Medication adherence today",
    voiceNotes: "Voice notes attached",
    aiSummary: "AI-generated summary",
    included: "Included",
    yourAccessCode: "Your access code",
    giveCodeToGP:
      "Give this code to your GP surgery so they can access your health summary.",
    copyCode: "Copy code",
    copied: "Copied",
    shareWithGP: "Share with my GP",
    sharedWithGP: "Shared with your GP",
    sharedConfirmation: "They can now see your health summary using code",
    revokeAccess: "Revoke access",
    entriesOverWeeks: (total, weeks) =>
      `${total} entries over ${weeks} week${weeks !== 1 ? "s" : ""}`,
    voiceNoteCount: (n) => `${n} note${n !== 1 ? "s" : ""}`,
  },
  capture: {
    title: "Appointment Capture",
    subtitle: "Record your consultation for your own records",
    bmaTitle: "Recording your appointment is encouraged",
    bmaText:
      "The BMA supports patients recording consultations for personal use. It helps you remember what was discussed and share it with carers or family. Your recording is stored only on this device.",
    tapToRecord: "Tap to start recording",
    transcriptionNote:
      "Your recording will be transcribed automatically when you stop.",
    consultationRecording: "Consultation recording",
    aiTranscription: "AI Transcription",
    autoGenerated: "Auto-generated",
    reRecord: "Record a new consultation",
  },
  reminders: {
    title: "Reminders",
    subtitle: "Your medication schedule for today",
    takenOfTotal: (taken, total) => `${taken} of ${total} taken today`,
    allTaken: "All medications taken — well done today.",
    stillToTake: (n) =>
      `${n} medication${n !== 1 ? "s" : ""} still to take today.`,
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    taken: "Taken",
    skip: "Skip",
    skipped: "Skipped",
    footerNote:
      "Taking your medications as prescribed helps your GP see how your treatment is working.",
  },
  chat: {
    title: "AI Health Companion",
    subtitle: "Supportive, informational — never a substitute for your GP",
    disclaimer:
      "This companion provides general health information, not medical advice.",
    placeholder: "Type a message…",
  },
};

const pl: Translations = {
  nav: {
    home: "Strona główna",
    dailyCare: "Opieka dzienna",
    gpBridge: "Pomost GP",
    capture: "Nagrywanie",
    reminders: "Przypomnienia",
  },
  home: {
    title: "Witaj, Mario",
    subtitle: "Twoje zdrowie, przejrzyście śledzone.",
    mostRecent: "Ostatnio",
    adherenceToday: "Adherencja dziś",
  },
  dailyCare: {
    title: "Opieka dzienna",
    subtitle: "Śledź swoje samopoczucie każdego dnia",
    totalLogged: "Łącznie wpisów",
    thisWeek: "W tym tygodniu",
    avgSeverity: "Śr. nasilenie",
    recordSymptom: "Dodaj objaw",
    recentEntries: "Ostatnie wpisy",
    noSymptoms: "Brak wpisów objawów.",
    symptomLabel: "Objaw",
    severityLabel: "Nasilenie",
    howItFeels: "Jak się czujesz?",
    dateLabel: "Data",
    notesLabel: "Uwagi",
    optional: "(opcjonalnie)",
    customPlaceholder: "Lub wpisz własny objaw…",
    descPlaceholder: "Opisz jak się czujesz…",
    notesPlaceholder: "Dodatkowy kontekst…",
    addVoiceNote: "Dodaj notatkę głosową",
    saveEntry: "Zapisz wpis",
    allFilter: "Wszystkie",
    symptomSeverity: "Nasilenie objawów",
    voiceNote: "1 notatka głosowa",
  },
  voice: {
    recording: "Nagrywanie",
    stop: "Zatrzymaj",
    cancel: "Anuluj",
    tapWhenDone: "Naciśnij Zatrzymaj, gdy skończysz",
  },
  severity: {
    veryMild: "Bardzo łagodny",
    mild: "Łagodny",
    moderate: "Umiarkowany",
    quiteBad: "Dość poważny",
    severe: "Poważny",
  },
  trend: {
    improving: "Poprawa",
    stable: "Stabilny",
    worsening: "Pogorszenie",
  },
  symptomNames: [
    "Ból głowy", "Zmęczenie", "Ból pleców", "Nudności", "Zawroty głowy",
    "Ucisk w klatce", "Ból stawów", "Duszność", "Ból żołądka",
    "Lęk", "Kołatanie serca", "Obrzęk kostek",
  ],
  gpBridge: {
    title: "Pomost GP",
    subtitle: "Udostępnij swój stan zdrowia lekarzowi",
    whatSharingDoes: "Co oznacza udostępnienie?",
    sharingExplanation:
      "Udostępnienie daje Twojemu lekarzowi przejrzysty, aktualny obraz Twoich ostatnich objawów, stosowania leków i notatek głosowych — przed wizytą, aby mógł się przygotować. Żadne dane osobowe nie opuszczają urządzenia bez Twojej zgody.",
    whatGPWillSee: "Co zobaczy Twój lekarz",
    symptomEntries: "Wpisy objawów",
    medicationAdherence: "Przyjmowanie leków dziś",
    voiceNotes: "Dołączone notatki głosowe",
    aiSummary: "Podsumowanie AI",
    included: "Dołączone",
    yourAccessCode: "Twój kod dostępu",
    giveCodeToGP:
      "Podaj ten kod w swojej przychodni, aby lekarz mógł uzyskać dostęp do Twojego podsumowania zdrowia.",
    copyCode: "Skopiuj kod",
    copied: "Skopiowano",
    shareWithGP: "Udostępnij lekarzowi",
    sharedWithGP: "Udostępniono lekarzowi",
    sharedConfirmation: "Lekarz może teraz zobaczyć Twoje podsumowanie, używając kodu",
    revokeAccess: "Cofnij dostęp",
    entriesOverWeeks: (total, weeks) =>
      `${total} wpisów przez ${weeks} tydzień${weeks > 1 ? "i" : ""}`,
    voiceNoteCount: (n) => `${n} notatk${n === 1 ? "a" : "i"}`,
  },
  capture: {
    title: "Nagrywanie wizyty",
    subtitle: "Nagraj konsultację na swój użytek",
    bmaTitle: "Nagrywanie wizyty jest zalecane",
    bmaText:
      "BMA popiera nagrywanie konsultacji przez pacjentów do użytku osobistego. Pomóże Ci zapamiętać rozmowę i podzielić się nią z opiekunami. Nagranie jest przechowywane tylko na tym urządzeniu.",
    tapToRecord: "Naciśnij, aby rozpocząć nagrywanie",
    transcriptionNote:
      "Nagranie zostanie automatycznie przepisane, gdy je zatrzymasz.",
    consultationRecording: "Nagranie konsultacji",
    aiTranscription: "Transkrypcja AI",
    autoGenerated: "Automatycznie wygenerowane",
    reRecord: "Nagraj nową konsultację",
  },
  reminders: {
    title: "Przypomnienia",
    subtitle: "Twój dzienny plan leków",
    takenOfTotal: (taken, total) => `${taken} z ${total} przyjętych dziś`,
    allTaken: "Wszystkie leki przyjęte — świetna robota!",
    stillToTake: (n) => `${n} lek${n > 1 ? "i" : ""} jeszcze do wzięcia dziś.`,
    morning: "Rano",
    afternoon: "Po południu",
    evening: "Wieczór",
    taken: "Przyjęto",
    skip: "Pomiń",
    skipped: "Pominięto",
    footerNote:
      "Regularne przyjmowanie leków pomaga lekarzowi ocenić skuteczność leczenia.",
  },
  chat: {
    title: "Asystent Zdrowotny AI",
    subtitle: "Wspierający, informacyjny — nie zastępuje lekarza",
    disclaimer:
      "Ten asystent dostarcza ogólnych informacji zdrowotnych, nie porad medycznych.",
    placeholder: "Wpisz wiadomość…",
  },
};

const ur: Translations = {
  nav: {
    home: "ہوم",
    dailyCare: "روزانہ نگہداشت",
    gpBridge: "جی پی بریج",
    capture: "ریکارڈنگ",
    reminders: "یادہانی",
  },
  home: {
    title: "خوش آمدید، ماریہ",
    subtitle: "آپ کی صحت، واضح طور پر مرتب ہے۔",
    mostRecent: "حال ہی میں",
    adherenceToday: "آج کی پابندی",
  },
  dailyCare: {
    title: "روزانہ نگہداشت",
    subtitle: "ہر روز اپنی صحت کا ریکارڈ رکھیں",
    totalLogged: "کل اندراجات",
    thisWeek: "اس ہفتے",
    avgSeverity: "اوسط شدت",
    recordSymptom: "علامت درج کریں",
    recentEntries: "حالیہ اندراجات",
    noSymptoms: "ابھی کوئی علامت درج نہیں۔",
    symptomLabel: "علامت",
    severityLabel: "شدت",
    howItFeels: "آپ کیسا محسوس کر رہے ہیں؟",
    dateLabel: "تاریخ",
    notesLabel: "نوٹس",
    optional: "(اختیاری)",
    customPlaceholder: "یا اپنی علامت لکھیں…",
    descPlaceholder: "بتائیں کیسا محسوس ہو رہے ہیں…",
    notesPlaceholder: "اضافی تفصیل…",
    addVoiceNote: "آواز نوٹ شامل کریں",
    saveEntry: "اندراج محفوظ کریں",
    allFilter: "سب",
    symptomSeverity: "علامات کی شدت",
    voiceNote: "۱ آواز نوٹ",
  },
  voice: {
    recording: "ریکارڈنگ",
    stop: "روکیں",
    cancel: "منسوخ",
    tapWhenDone: "ختم ہونے پر روکیں دبائیں",
  },
  severity: {
    veryMild: "بہت ہلکی",
    mild: "ہلکی",
    moderate: "اعتدال",
    quiteBad: "کافی بری",
    severe: "شدید",
  },
  trend: {
    improving: "بہتری",
    stable: "مستحکم",
    worsening: "بگاڑ",
  },
  symptomNames: [
    "سر درد", "تھکان", "کمر کا درد", "متلی", "چکر",
    "سینے کی تنگی", "جوڑوں کا درد", "سانس لینے میں دشواری", "پیٹ درد",
    "گھبراہٹ", "دل کی دھڑکن", "پندلیوں کی سوجن",
  ],
  gpBridge: {
    title: "جی پی بریج",
    subtitle: "اپنی صحت کی تصویر اپنے ڈاکٹر سے شیئر کریں",
    whatSharingDoes: "شیئر کرنے کا مطلب کیا ہے؟",
    sharingExplanation:
      "شیئر کرنے سے آپ کے ڈاکٹر کو آپ کی حالیہ علامات، دوائیوں کی پابندی اور آواز نوٹس کی واضح تصویر ملتی ہے — ملاقات سے پہلے، تاکہ وہ تیار ہوں۔ آپ کی اجازت کے بغیر کوئی ذاتی ڈیٹا آپ کے آلے سے نہیں جائے گیا۔",
    whatGPWillSee: "آپ کا ڈاکٹر کیا دیکھے گا",
    symptomEntries: "علامات کے اندراجات",
    medicationAdherence: "آج دوائیں لینے کی پابندی",
    voiceNotes: "آواز نوٹ منسلک",
    aiSummary: "AI تجزیہ",
    included: "شامل",
    yourAccessCode: "آپ کا رسائی کوڈ",
    giveCodeToGP:
      "یہ کوڈ اپنی جی پی سرجری کو دیں تاکہ وہ آپ کی صحت کی تفصیل دیکھ سکیں۔",
    copyCode: "کوڈ کاپی کریں",
    copied: "کاپی ہو گئی",
    shareWithGP: "اپنے ڈاکٹر سے شیئر کریں",
    sharedWithGP: "آپ کے ڈاکٹر سے شیئر ہو گیا",
    sharedConfirmation: "وہ اب کوڈ کے ذریعے آپ کی صحت کی تفصیل دیکھ سکتے ہیں",
    revokeAccess: "رسائی منسوخ کریں",
    entriesOverWeeks: (total, weeks) =>
      `${total} اندراجات ، ${weeks} ہفتوں میں`,
    voiceNoteCount: (n) => `${n} نوٹ`,
  },
  capture: {
    title: "ملاقات کی ریکارڈنگ",
    subtitle: "اپنے ذاتی ریکارڈ کے لیے مشاورت ریکارڈ کریں",
    bmaTitle: "ملاقات ریکارڈ کرنا تجویز ہے",
    bmaText:
      "BMA مریضوں کو ذاتی استعمال کے لیے مشاورت ریکارڈ کرنے کی حمایت کرتی ہے۔ یہ آپ کو گفتگو یاد رکھنے میں مدد کرتی ہے۔ ریکارڈنگ صرف اس آلے پر محفوظ ہے۔",
    tapToRecord: "ریکارڈنگ شروع کرنے کے لیے ٹیپ کریں",
    transcriptionNote:
      "ریکارڈنگ روکنے پر خودبخود لکھائی جائے گی۔",
    consultationRecording: "مشاورت کی ریکارڈنگ",
    aiTranscription: "AI تحریر",
    autoGenerated: "خودبخود تیار",
    reRecord: "نئی مشاورت ریکارڈ کریں",
  },
  reminders: {
    title: "یادہانی",
    subtitle: "آج کا دوائی کا شیڈول",
    takenOfTotal: (taken, total) =>
      `آج ${total} میں سے ${taken} دوائیں لی گئیں`,
    allTaken: "تمام دوائیں لی گئی — شاباش۔",
    stillToTake: (n) => `${n} دوائیں ابھی باقی ہیں۔`,
    morning: "صبح",
    afternoon: "دوپہر",
    evening: "شام",
    taken: "لے لی",
    skip: "چھوڑیں",
    skipped: "چھوڑ دی",
    footerNote:
      "تجویز کے مطابق دوائیں لینا آپ کے ڈاکٹر کو علاج کی کارگزاری جانچنے میں مدد کرتا ہے۔",
  },
  chat: {
    title: "AI صحت ساتھی",
    subtitle: "معاون، معلوماتی — ڈاکٹر کا متبادل نہیں",
    disclaimer:
      "یہ ساتھی عام صحت کی معلومات فراہم کرتا ہے، طبی مشورہ نہیں۔",
    placeholder: "پیغام لکھیں…",
  },
};

const pa: Translations = {
  nav: {
    home: "ہوم",
    dailyCare: "روزانہ سنبھال",
    gpBridge: "جی پی برک",
    capture: "ریکارڈ",
    reminders: "یاددہانی",
  },
  home: {
    title: "جی آیاں، ماریہ",
    subtitle: "تہاڈی صحت، ساف طور تے رکورڈ ہے۔",
    mostRecent: "تازہ ترین",
    adherenceToday: "اج دی پابندی",
  },
  dailyCare: {
    title: "روزانہ سنبھال",
    subtitle: "ہر روز اپنی صحت دا ریکارڈ رکھو",
    totalLogged: "کل اندراج",
    thisWeek: "اس ہفتے",
    avgSeverity: "اوسط شدت",
    recordSymptom: "علامت درج کرو",
    recentEntries: "تازہ اندراج",
    noSymptoms: "ھجے کوئی علامت درج نئیں۔",
    symptomLabel: "علامت",
    severityLabel: "شدت",
    howItFeels: "تسیں کیوں محسوس کر رہے ہو؟",
    dateLabel: "تاریخ",
    notesLabel: "نوٹ",
    optional: "(اختیاری)",
    customPlaceholder: "یا اپنی علامت لکھو…",
    descPlaceholder: "دسو کیوں محسوس ہو رہے ہو…",
    notesPlaceholder: "وادھو تفصیل…",
    addVoiceNote: "آواز نوٹ پاؤ",
    saveEntry: "اندراج محفوظ کرو",
    allFilter: "سب",
    symptomSeverity: "علامات دی شدت",
    voiceNote: "۱ آواز نوٹ",
  },
  voice: {
    recording: "ریکارڈنگ",
    stop: "روکو",
    cancel: "منسوخ",
    tapWhenDone: "ختم ہون تے روکو دباؤ",
  },
  severity: {
    veryMild: "بہت ہلکی",
    mild: "ہلکی",
    moderate: "اعتدال",
    quiteBad: "کافی مڑا",
    severe: "شدید",
  },
  trend: {
    improving: "بہتری",
    stable: "مستحکم",
    worsening: "بگڑ",
  },
  symptomNames: [
    "سر درد", "تھکاوٹ", "کمر درد", "متلی", "چکر",
    "سینے دی کساوٹ", "جوڑاں درد", "ساہ لین ویچ مشکل", "پیٹ درد",
    "گھبراہٹ", "دل دی ہھڑکن", "ٹخنیاں سوجنا",
  ],
  gpBridge: {
    title: "جی پی برک",
    subtitle: "اپنی صحت دی تصویر اپنے ڈاکٹر نال شیئر کرو",
    whatSharingDoes: "شیئر کرن دا مطلب کی اے؟",
    sharingExplanation:
      "شیئر کرن نال تہاڈے ڈاکٹر نوں تہاڈیاں حالیہ علامات، دوائیاں لین دی پابندی اتے آواز نوٹس دی ساف تصویر ملدی اے — ملاقات توں پہلاں۔ تہاڈی اجازت توں بغیر کوئی ذاتی ڈیٹا نہیں جاندا۔",
    whatGPWillSee: "تہاڈا ڈاکٹر کیا ویکھے گا",
    symptomEntries: "علامات دے اندراج",
    medicationAdherence: "اج دوائیاں لین دی پابندی",
    voiceNotes: "آواز نوٹ منسلک",
    aiSummary: "AI خلاصہ",
    included: "شامل",
    yourAccessCode: "تہاڈا رسائی کوڈ",
    giveCodeToGP:
      "یہ کوڈ اپنی جی پی سرجری نوں دہو تاکہ اوہ تہاڈہ صحت دی تفصیل ویکھ سکن۔",
    copyCode: "کوڈ کاپی کرو",
    copied: "کاپی ہو گئی",
    shareWithGP: "اپنے ڈاکٹر نال شیئر کرو",
    sharedWithGP: "تہاڈے ڈاکٹر نال شیئر ہو گیا",
    sharedConfirmation: "اوہ ہن کوڈ راہیں تہاڈی صحت دی تفصیل ویکھ سکدے نے",
    revokeAccess: "رسائی واپس کرو",
    entriesOverWeeks: (total, weeks) =>
      `${total} اندراج، ${weeks} ہفتیاں ویچ`,
    voiceNoteCount: (n) => `${n} نوٹ`,
  },
  capture: {
    title: "ملاقات ریکارڈنگ",
    subtitle: "اپنے ریکارڈ لئی مشاورت ریکارڈ کرو",
    bmaTitle: "ملاقات ریکارڈ کرنا جائز اے",
    bmaText:
      "BMA مریضاں نوں ذاتی استعمال لئی مشاورت ریکارڈ کرن دی حمایت کردی اے۔ ریکارڈنگ صرف اس آلے تے محفوظ اے۔",
    tapToRecord: "ریکارڈنگ شروع کرن لئی ٹیپ کرو",
    transcriptionNote:
      "ریکارڈنگ روکن تے خودبخود لکھی جاوے گی۔",
    consultationRecording: "مشاورت دی ریکارڈنگ",
    aiTranscription: "AI تحریر",
    autoGenerated: "خودبخود تیار",
    reRecord: "نویں مشاورت ریکارڈ کرو",
  },
  reminders: {
    title: "یاددہانی",
    subtitle: "اج دا دوائی شیڈول",
    takenOfTotal: (taken, total) =>
      `اج ${total} ویچوں ${taken} دوائیاں لیتیاں`,
    allTaken: "ساریاں دوائیاں لیتیاں — شاباش۔",
    stillToTake: (n) => `${n} دوائیاں ھجے باقی نے۔`,
    morning: "سویرے",
    afternoon: "دوپہر",
    evening: "شام",
    taken: "لے لئی",
    skip: "چھڑو",
    skipped: "چھڑ دتی",
    footerNote:
      "دوائیاں نیم نال لینا تہاڈے ڈاکٹر نوں علاج دی سمائی جانچن ویچ مدد کردا اے۔",
  },
  chat: {
    title: "AI صحت ساتھی",
    subtitle: "مددگار، معلوماتی — ڈاکٹر دا متبادل نئیں",
    disclaimer:
      "یہ ساتھی عام صحت جانکاری دیندا اے، طبی مشورہ نئیں۔",
    placeholder: "سندےس لکھو…",
  },
};

export const translations: Record<Language, Translations> = { en, pl, ur, pa };
